kind: ConfigMap
apiVersion: v1
metadata:
  name: akvo
  namespace: default
data:
  keycloak.url: https://login.akvo.org/auth
  email.host: mail.akvo.org
  flow.api.root: https://api.akvotest.org/flow
